### PR TITLE
Add more frontend tools to the radar

### PR DESCRIPTION
**Pull request by T0RAT0RA**

### CODE REVIEW

**Comment by T0RAT0RA** [comment]
@AlayaCare/team-sloths @AlayaCare/team-octopus, team lions is building a [Tech radar](https://www.thoughtworks.com/radar) for AlayaCare Cloud, and I'm adding some of our relevant frontend tools.
What do you think we should put in there in terms, in terms of technology that we should either adopt, or put on hold?

The Radar is deployed here: [AlayaCare Cloud Tech Radar](https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Falayacare.github.io%2Falayacare-cloud-radar%2FAlayaCare%20Cloud%20Tech%20Radar.csv)

**Comment by poblouin** [comment]
Typescript and Rollup

**Comment by T0RAT0RA** [comment]
> Typescript and Rollup

Typescript: Assess
Rollup: Trial

?

**Comment by poblouin** [comment]
> > Typescript and Rollup
> 
> Typescript: Assess
> Rollup: Trial
> 
> ?

Yes sorry, should have specified

**Comment by et1421** [comment]
Should tool like Eslint/prettier (Adopt) and stylelint (Trial)  be there ?
LESS: Hold
SCSS: Adopt
Accessibility: Assess 
jQuery: hold
Bootstrap: Hold
require.js: Hold
t3: Hold
vue1: Hold
Jest: Adopt
vue-test-utils: Adopt
Cypress: Adopt

Should legacy technology be there 🤔 ? Is the idea to have all tech here? (I guess so if github is there)

**Pull request merged**
